// @ts-check
import { readFile, writeFile } from 'node:fs/promises';
import { defineConfig, envField } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import { normalizeBase, withTrailingSlash } from './src/lib/paths.mjs';
import { REDIRECTS, EXTERNAL_REDIRECTS, SUBSPLASH_MEDIA } from './src/lib/redirects.mjs';

// ---- Where the site is served from -------------------------------------------------------------
// SITE_URL   full public address: https://springoflifechurch.com (default), a *.pages.dev
//            address, or https://<user>.github.io/<repo>/ for a GitHub Pages project site.
// BASE_PATH  sub-path the site lives under. Defaults to the path part of SITE_URL, so
//            SITE_URL=https://<user>.github.io/<repo>/ alone is enough. Empty counts as unset
//            (GitHub Actions passes an unset repository variable as "").
// PREVIEW    "true" while this isn't the public church site yet: every page gets
//            noindex,nofollow, robots.txt disallows everything, and no sitemap is generated.
const siteUrl = new URL(process.env.SITE_URL || 'https://springoflifechurch.com');
const base = normalizeBase(process.env.BASE_PATH || siteUrl.pathname);
const prefix = base.slice(0, -1); // "" or "/repo"
const preview = process.env.PREVIEW === 'true';
const target = (/** @type {string} */ to) => prefix + withTrailingSlash(to);

/** Cloudflare Pages `_redirects`: real 301s for old SnapPages URLs, incl. old sermon pages. */
const hostRedirects = () => [
  '# Generated by astro.config.mjs from src/lib/redirects.mjs. Used by Cloudflare Pages only;',
  '# GitHub Pages ignores this file and serves the meta-refresh pages instead.',
  ...Object.entries(REDIRECTS).flatMap(([from, to]) => [`${prefix}${from} ${target(to)} 301`, `${prefix}${from}/ ${target(to)} 301`]),
  ...Object.entries(EXTERNAL_REDIRECTS).map(([from, to]) => `${prefix}${from} ${to} 301`),
  `${prefix}/media/series/:code/* ${SUBSPLASH_MEDIA}/ms/+:code 301`,
  `${prefix}/media/series/:code ${SUBSPLASH_MEDIA}/ms/+:code 301`,
  `${prefix}/media/:code/* ${SUBSPLASH_MEDIA}/mi/+:code 301`,
  `${prefix}/media/* ${target('/watch')} 301`, // anything else under the old /media/ (nothing is served there now)
  '',
].join('\n');

export default defineConfig({
  site: siteUrl.origin,
  base,
  output: 'static',
  trailingSlash: 'ignore',
  // Meta-refresh pages for static hosts without server redirects (GitHub Pages).
  redirects: {
    ...Object.fromEntries(Object.entries(REDIRECTS).map(([from, to]) => [from, target(to)])),
    ...EXTERNAL_REDIRECTS,
  },
  env: {
    schema: {
      PREVIEW: envField.boolean({ context: 'server', access: 'public', default: false }),
    },
  },
  integrations: [
    ...(preview ? [] : [sitemap({
      filter: (page) => {
        const path = new URL(page).pathname.slice(prefix.length).replace(/\/$/, '') || '/';
        return !(path in REDIRECTS) && !(path in EXTERNAL_REDIRECTS);
      },
    })]),
    {
      name: 'sol-host-files',
      hooks: {
        'astro:build:done': async ({ dir, logger }) => {
          await writeFile(new URL('_redirects', dir), hostRedirects());
          // The SnapPages events widget: public/embed/sol-events.js is the readable source; the
          // published copy is minified (budget: 6 KB, checked by npm test).
          const widget = new URL('embed/sol-events.js', dir);
          try {
            const { transform } = await import('esbuild');
            const { code } = await transform(await readFile(widget, 'utf8'), { minify: true, target: 'es2017', legalComments: 'inline' });
            await writeFile(widget, code);
          } catch (err) {
            logger.warn(`embed/sol-events.js was published unminified: ${err instanceof Error ? err.message : err}`);
          }
        },
      },
    },
  ],
  image: { responsiveStyles: false },
  // No code blocks on this site; Shiki's inline styles would also conflict with the CSP below.
  markdown: { syntaxHighlight: false },
  // Content-Security-Policy as a <meta> tag (GitHub Pages can't send headers). Astro adds
  // script-src/style-src with 'self' plus the hash of every script and style it renders, so no
  // inline event handler or injected <script> can run. Subsplash is the only allowed frame.
  // `data:` covers the one tiny font file Vite inlines and the brand mark used as a CSS mask.
  security: {
    csp: {
      directives: [
        "default-src 'self'",
        "img-src 'self' data:",
        "font-src 'self' data:",
        'frame-src https://subsplash.com',
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'self'",
      ],
    },
  },
});
