// "This week at Spring of Life" — a plain template filled from the event feed.
// No AI: same input, same text. A person copies it into the bulletin or Telegram after reviewing it.
import { formatLongDate, formatRange, startOfLocalDay } from '../../src/lib/time.mjs';

const DAY = 86_400_000;

function nextSunday(now) {
  for (let i = 0; i < 7; i++) {
    const d = startOfLocalDay(now.toISOString(), i);
    if (formatLongDate(new Date(d.getTime() + DAY / 2).toISOString()).startsWith('Sunday')) return new Date(d.getTime() + DAY / 2);
  }
  return null;
}

function eventBlock(e) {
  const where = e.location?.name || e.location?.address;
  const lines = [`**${e.title}**`, [formatRange(e), where].filter(Boolean).join(' · ')];
  if (e.summary) lines.push(e.summary);
  const cta = e.register_url && e.registration.open && !e.registration.full ? 'Register' : 'Details';
  lines.push([e.price?.label, `${cta}: ${e.details_url}`].filter(Boolean).join(' · '));
  return lines.join('\n');
}

export function buildDigest(events, { now, site, siteUrl }) {
  const start = startOfLocalDay(now.toISOString());
  const end = startOfLocalDay(now.toISOString(), 7); // not start + 7×24 h: a week can have 167 or 169 hours
  const inWeek = events.filter((e) => e.starts_at && new Date(e.starts_at) < end);
  const later = events.filter((e) => e.starts_at && new Date(e.starts_at) >= end && new Date(e.starts_at) < new Date(start.getTime() + 60 * DAY)).slice(0, 4);
  const closing = events.filter((e) => e.registration.open && e.registration.closes_at
    && new Date(e.registration.closes_at) > now && new Date(e.registration.closes_at) < new Date(now.getTime() + 7 * DAY));
  const sunday = nextSunday(now);
  const lastDay = new Date(end.getTime() - DAY / 2).toISOString();

  const out = [
    '<!-- Generated by scripts/sync.mjs from the website event feed. Do not edit here; edit the copy you post. -->',
    `# This week at ${site.name}`,
    `_${formatLongDate(start.toISOString(), { year: false })} – ${formatLongDate(lastDay, { year: true })}_`,
    '',
    '> **DRAFT. A person reviews this before it is posted.** It is built automatically from Planning Center signups that carry the website category. Check names, dates and links, then copy it into the bulletin or Telegram.',
    '',
    '## Sunday worship',
    `Join us ${sunday ? formatLongDate(sunday.toISOString()) : 'Sunday'} at ${site.service.time} · ${site.address.street}, ${site.address.city}, ${site.address.region}`,
    `Watch live: ${site.links.youtube_live}`,
    '',
    '## This week',
    inWeek.length ? inWeek.map(eventBlock).join('\n\n') : '_No website events this week._',
  ];
  if (later.length) out.push('', '## Coming up', later.map((e) => `- **${e.title}**, ${formatRange(e)}: ${e.details_url}`).join('\n'));
  if (closing.length) out.push('', '## Registration closing soon', closing.map((e) => `- **${e.title}**: registration closes ${formatRange({ starts_at: e.registration.closes_at })}`).join('\n'));
  out.push('', '---', `All events: ${siteUrl}/events · Give: ${site.links.give} · Life Groups: ${siteUrl}/life-groups`, '');
  return out.join('\n');
}
